"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Layout, Menu } from "antd";
import Link from "next/link";
import { RootState, store } from "./redux/store";
import { Provider, useSelector } from "react-redux";
import AppHeader from "./components/AppHeader";
const { Header, Content, Footer } = Layout;

const inter = Inter({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          <Layout
            style={{
              minHeight: "100vh",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <AppHeader />
            <Content style={{ padding: "0 50px", flex: 1 }}>{children}</Content>
            <Footer>
              <footer>Footer</footer>
            </Footer>
          </Layout>
        </body>
      </html>
    </Provider>
  );
}
